// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy1oL3rSrwsyBlIS8LO6NaRMMA08cxtrs',
    appId: '1:852019744450:android:0cc60a52fb7e3fc281f55b',
    messagingSenderId: '852019744450',
    projectId: 'push-notification-demo-91b41',
    storageBucket: 'push-notification-demo-91b41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCafujefh0VuPzz6iSUnThek437h7r6Vow',
    appId: '1:852019744450:ios:a1aa948afcc6b3f581f55b',
    messagingSenderId: '852019744450',
    projectId: 'push-notification-demo-91b41',
    storageBucket: 'push-notification-demo-91b41.appspot.com',
    androidClientId: '852019744450-02c4uh4q7pt64cr05to6vv98p67d8ipt.apps.googleusercontent.com',
    iosClientId: '852019744450-lhf9fuv7e41jdj9to6vk51hr8401bjon.apps.googleusercontent.com',
    iosBundleId: 'net.appdevs.adbot',
  );
}
